export const KoreaList=[
  { id: 1, city: "도쿄" },
  { id: 2, city: "오사카" },
  { id: 3, city: "오이타" },
  { id: 4, city: "후쿠오카" },
  { id: 5, city: "삿포로" },
  { id: 6, city: "베이징" },
  { id: 7, city: "상하이" },
  { id: 8, city: "다낭" },
  { id: 9, city: "호치민" },
  { id: 10, city: "나트랑" },
  { id: 11, city: "파리" },
  { id: 12, city: "니스" },
  { id: 13, city: "스위스" },
  { id: 14, city: "이탈리아" },
  { id: 15, city: "스페인" },
  { id: 16, city: "독일" },
  { id: 17, city: "오스트리아" },
  { id: 18, city: "네덜란드" },
  { id: 19, city: "체코" },
  { id: 20, city: "그리스" },
  { id: 21, city: "뉴욕" },
  { id: 22, city: "로스앤젤레스" },
  { id: 23, city: "밴쿠버" },
  { id: 24, city: "토론토" },
  { id: 25, city: "멕시코시티" },
  { id: 26, city: "리우데자네이루" },
  { id: 27, city: "상파울루" },
  { id: 28, city: "리마" },
  { id: 29, city: "산티아고" },
  { id: 30, city: "부에노스아이레스" },

  { id: 101, city: "제주도" },
  { id: 102, city: "부산" },
  { id: 103, city: "강릉" },
  { id: 104, city: "경주" },
  { id: 105, city: "서울" }
]