export const PackageList=[
       {
    id: 1,
    image: "/images/country/1.country_asia/1.j1.jpg",
    title: "봄맞이 도쿄 여행 특가",
    price: "₩ 999,000~",
    country: "Japan",
    type: "overseas", // 해외
    buttonText: "바로가기 〉",
    rating: 4.3,
    reviewCount: 100,
    contient: 'Asia',
    link: "/Package/overeas/Asia/Japan/1"
  },
  {
    id: 2,
    image: "/images/country/1.country_asia/2.j2.jpg",
    title: "먹거리 가득 오사카 여행",
    price: "₩ 759,000~",
    country: "Japan",
    city: "Osaka",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.4,
    reviewCount: 128,
    contient: 'Asia',
    link: "/Package/overeas/Asia/Japan/2"
  },
  {
    id: 3,
    image: "/images/country/1.country_asia/3.j3.jpg",
    title: "온천으로 떠나는 오이타 여행",
    price: "₩ 939,000~",
    country: "Japan",
    city: "Oita",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.2,
    reviewCount: 73,
    contient: 'Asia',
    link: "/Package/overeas/Asia/Japan/3"
  },
  {
    id: 4,
    image: "/images/country/1.country_asia/4.j4.jpg",
    title: "가볍게 떠나기 좋은 후쿠오카 여행",
    price: "₩ 699,000~",
    country: "Japan",
    city: "Fukuoka",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.6,
    reviewCount: 154,
    contient: 'Asia',
    link: "/Package/overeas/Asia/Japan/4"
  },
  {
    id: 5,
    image: "/images/country/1.country_asia/5.j5.jpg",
    title: "감성 가득 삿포로 여행",
    price: "₩ 1,150,000~",
    country: "Japan",
    city: "Sapporo",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.7,
    reviewCount: 191,
    contient: 'Asia',
    link: "/Package/overeas/Asia/Japan/5"
  },
  {
    id: 6,
    image: "/images/country/1.country_asia/6.c1.jpg",
    title: "역사를 찾아 떠나는 베이징 여행",
    price: "₩ 2,299,000~",
    country: "China",
    city: "Beijing",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.3,
    reviewCount: 203,
    contient: 'Asia',
    link: "/Package/overeas/Asia/China/6"
  },
  {
    id: 7,
    image: "/images/country/1.country_asia/7.c2.jpg",
    title: "화려한 야경의 상하이 여행",
    price: "₩ 1,899,000~",
    country: "China",
    city: "Shanghai",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.5,
    reviewCount: 187,
    contient: 'Asia',
    link: "/Package/overeas/Asia/China/7"
  },
  {
    id: 8,
    image: "/images/country/1.country_asia/8.b1.jpg",
    title: "휴양과 바다를 즐기는 다낭 여행",
    price: "₩ 859,000~",
    country: "Vietnam",
    city: "Danang",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.6,
    reviewCount: 214,
    contient: 'Asia',
    link: "/Package/overeas/Asia/Vietnam/8"
  },
  {
    id: 9,
    image: "/images/country/1.country_asia/9.b2.jpg",
    title: "활기찬 매력의 호치민 여행",
    price: "₩ 829,000~",
    country: "Vietnam",
    city: "Ho Chi Minh",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.3,
    reviewCount: 189,
    contient: 'Asia',
    link: "/Package/overeas/Asia/Vietnam/9"
  },
  {
    id: 10,
    image: "/images/country/1.country_asia/10.b3.jpg",
    title: "에메랄드 바다의 나트랑 여행",
    price: "₩ 899,000~",
    country: "Vietnam",
    city: "Nha Trang",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.5,
    reviewCount: 158,
    contient: 'Asia',
    link: "/Package/overeas/Asia/Vietnam/10"
  },
  {
    id: 11,
    image: "/images/country/2.country_europe/1.f1.jpg",
    title: "낭만의 도시 파리 여행",
    price: "₩ 1,799,000~",
    country: "France",
    city: "Paris",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.3,
    reviewCount: 203,
    contient: 'Europe',
    link: "/Package/overeas/Europe/France/11"
  },
  {
    id: 12,
    image: "/images/country/2.country_europe/2.f2.jpg",
    title: "지중해 감성 니스 여행",
    price: "₩ 1,659,000~",
    country: "France",
    city: "Nice",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.5,
    contient: 'Europe',
    reviewCount: 167,
    link: "/Package/overeas/Europe/France/12"
  },
  {
    id: 13,
    image: "/images/country/2.country_europe/3.sw.jpg",
    title: "알프스 감성 가득한 스위스 여행",
    price: "₩ 2,299,000~",
    country: "Switzerland",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.8,
    reviewCount: 221,
    contient: 'Europe',
    link: "/Package/overeas/Europe/Switzerland/13"
  },
  {
    id: 14,
    image: "/images/country/2.country_europe/4.it.jpg",
    title: "예술과 낭만의 이탈리아 여행",
    price: "₩ 2,099,000~",
    country: "Italy",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.7,
    contient: 'Europe',
    reviewCount: 198,
    link: "/Package/overeas/Europe/Italy/14"
  },
  {
    id: 15,
    image: "/images/country/2.country_europe/5.spa.jpg",
    title: "열정이 넘치는 스페인 여행",
    price: "₩ 1,989,000~",
    country: "Spain",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.6,
    contient: 'Europe',
    reviewCount: 176,
    link: "/Package/overeas/Europe/Spain/15"
  },
  {
    id: 16,
    image: "/images/country/2.country_europe/6.G.jpg",
    title: "감성과 전통이 공존하는 독일 여행",
    price: "₩ 2,159,000~",
    country: "Germany",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.5,
    contient: 'Europe',
    reviewCount: 164,
    link: "/Package/overeas/Europe/Germany/16"
  },
  {
    id: 17,
    image: "/images/country/2.country_europe/7.a.jpg",
    title: "음악과 풍경이 아름다운 오스트리아 여행",
    price: "₩ 2,189,000~",
    country: "Austria",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.7,
    contient: 'Europe',
    reviewCount: 182,
    link: "/Package/overeas/Europe/Austria/17"
  },
  {
    id: 18,
    image: "/images/country/2.country_europe/8.nl.jpg",
    title: "운하의 도시 네덜란드 여행",
    price: "₩ 2,049,000~",
    country: "Netherlands",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.4,
    contient: 'Europe',
    reviewCount: 151,
    link: "/Package/overeas/Europe/Netherlands/18"
  },
  {
    id: 19,
    image: "/images/country/2.country_europe/9.cz.jpg",
    title: "동화 같은 풍경의 체코 여행",
    price: "₩ 1,939,000~",
    country: "Czech Republic",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.6,
    contient: 'Europe',
    reviewCount: 169,
    link: "/Package/overeas/Europe/Czech Republic/19"
  },
  {
    id: 20,
    image: "/images/country/2.country_europe/10.gr.jpg",
    title: "눈부신 지중해의 그리스 여행",
    price: "₩ 2,129,000~",
    country: "Greece",
    type: "overseas",
    buttonText: "바로가기 〉",
    contient: 'Europe',
    rating: 4.5,
    reviewCount: 158,
    link: "/Package/overeas/Europe/Greece/20"
  },
  {
    id: 21,
    image: "/images/country/3.country_americas/1.usa1.jpg",
    title: "화려한 도시의 매력 뉴욕 여행",
    price: "₩ 2,399,000~",
    country: "USA",
    city: "New York",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.7,
    contient: 'America',
    reviewCount: 245,
    link: "/Package/overeas/America/New York/21"
  },
  {
    id: 22,
    image: "/images/country/3.country_americas/2.usa2.jpg",
    title: "자유로운 감성의 로스앤젤레스 여행",
    price: "₩ 2,289,000~",
    country: "USA",
    city: "Los Angeles",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.6,
    reviewCount: 214,
    contient: 'America',
    link: "/Package/overeas/America/Losangeles/22"
  },
  {
    id: 23,
    image: "/images/country/3.country_americas/3.ca1.jpg",
    title: "자연과 도시가 어우러진 밴쿠버 여행",
    price: "₩ 2,159,000~",
    country: "Canada",
    city: "Vancouver",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.5,
    reviewCount: 182,
    contient: 'America',
    link: "/Package/overeas/America/Vancouver/23"
  },
  {
    id: 24,
    image: "/images/country/3.country_americas/4.ca2.jpg",
    title: "세련된 도심 속 토론토 여행",
    price: "₩ 2,199,000~",
    country: "Canada",
    city: "Toronto",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.4,
    contient: 'America',
    reviewCount: 169,
    link: "/Package/overeas/America/Toronto/24"
  },
  {
    id: 25,
    image: "/images/country/3.country_americas/5.mex.jpg",
    title: "전통과 열정이 살아있는 멕시코시티 여행",
    price: "₩ 1,989,000~",
    country: "Mexico",
    city: "Mexico City",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.3,
    contient: 'America',
    reviewCount: 151,
    link: "/Package/overeas/America/Mexicocity/25"
  },
  {
    id: 26,
    image: "/images/country/3.country_americas/6.br.jpg",
    title: "열정의 해변 도시 리우 여행",
    price: "₩ 2,499,000~",
    country: "Brazil",
    city: "Rio de Janeiro",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.7,
    contient: 'America',
    reviewCount: 203,
    link: "/Package/overeas/America/Rio/26"
  },
  {
    id: 27,
    image: "/images/country/3.country_americas/7.br.jpg",
    title: "브라질의 활기를 느끼는 상파울루 여행",
    price: "₩ 2,359,000~",
    country: "Brazil",
    city: "Sao Paulo",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.2,
    contient: 'America',
    reviewCount: 144,
    link: "/Package/overeas/America/Sao Paulo/27"
  },
  {
    id: 28,
    image: "/images/country/3.country_americas/8.p.jpg",
    title: "역사와 미식이 공존하는 리마 여행",
    price: "₩ 2,189,000~",
    country: "Peru",
    city: "Lima",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.4,
    contient: 'America',
    reviewCount: 137,
    link: "/Package/overeas/America/Lima/28"
  },
  {
    id: 29,
    image: "/images/country/3.country_americas/9.chi.jpg",
    title: "안데스의 풍경을 담은 산티아고 여행",
    price: "₩ 2,279,000~",
    country: "Chile",
    city: "Santiago",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.3,
    contient: 'America',
    reviewCount: 129,
    link: "/Santiago"
  },
  {
    id: 30,
    image: "/images/country/3.country_americas/10.arg.jpg",
    title: "낭만과 정열의 부에노스아이레스 여행",
    price: "₩ 2,469,000~",
    country: "Argentina",
    city: "Buenos Aires",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.6,
    contient: 'America',
    reviewCount: 158,
    link: "/buenosaires"

    
  }
] 