export const PackageList=[
       {
    id: 1,
    image: "/img/paris.jpg",
    title: "봄맞이 도쿄 여행 특가",
    price: "₩ 999,000~",
    country: "Japan",
    type: "overseas", // 해외
    buttonText: "바로가기 〉",
    rating: 4.3,
    reviewCount: 100,
    link: "/tokyo"
  },
  {
    id: 2,
    image: "/img/osaka.jpg",
    title: "먹거리 가득 오사카 여행",
    price: "₩ 759,000~",
    country: "Japan",
    city: "Osaka",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.4,
    reviewCount: 128,
    link: "/osaka"
  },
  {
    id: 3,
    image: "/img/oita.jpg",
    title: "온천으로 떠나는 오이타 여행",
    price: "₩ 939,000~",
    country: "Japan",
    city: "Oita",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.2,
    reviewCount: 73,
    link: "/oita"
  },
  {
    id: 4,
    image: "/img/fukuoka.jpg",
    title: "가볍게 떠나기 좋은 후쿠오카 여행",
    price: "₩ 699,000~",
    country: "Japan",
    city: "Fukuoka",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.6,
    reviewCount: 154,
    link: "/fukuoka"
  },
  {
    id: 5,
    image: "/img/sapporo.jpg",
    title: "감성 가득 삿포로 여행",
    price: "₩ 1,150,000~",
    country: "Japan",
    city: "Sapporo",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.7,
    reviewCount: 191,
    link: "/sapporo"
  },
   {
    id: 6,
    image: "/img/beijing.jpg",
    title: "역사를 찾아 떠나는 베이징 여행",
    price: "₩ 2,299,000~",
    country: "China",
    city: "Beijing",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.3,
    reviewCount: 203,
    link: "/beijing"
  },
  {
    id: 7,
    image: "/img/shanghai.jpg",
    title: "화려한 야경의 상하이 여행",
    price: "₩ 1,899,000~",
    country: "China",
    city: "Shanghai",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.5,
    reviewCount: 187,
    link: "/shanghai"
  },
  {
    id: 8,
    image: "/img/danang.jpg",
    title: "휴양과 바다를 즐기는 다낭 여행",
    price: "₩ 859,000~",
    country: "Vietnam",
    city: "Danang",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.6,
    reviewCount: 214,
    link: "/danang"
  },
  {
    id: 9,
    image: "/img/hochiminh.jpg",
    title: "활기찬 매력의 호치민 여행",
    price: "₩ 829,000~",
    country: "Vietnam",
    city: "Ho Chi Minh",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.3,
    reviewCount: 189,
    link: "/hochiminh"
  },
  {
    id: 10,
    image: "/img/nhatrang.jpg",
    title: "에메랄드 바다의 나트랑 여행",
    price: "₩ 899,000~",
    country: "Vietnam",
    city: "Nha Trang",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.5,
    reviewCount: 158,
    link: "/nhatrang"
  },
   {
    id: 11,
    image: "/img/paris.jpg",
    title: "낭만의 도시 파리 여행",
    price: "₩ 1,799,000~",
    country: "France",
    city: "Paris",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.3,
    reviewCount: 203,
    link: "/paris"
  },
  {
    id: 12,
    image: "/img/nice.jpg",
    title: "지중해 감성 니스 여행",
    price: "₩ 1,659,000~",
    country: "France",
    city: "Nice",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.5,
    reviewCount: 167,
    link: "/nice"
  },
  {
    id: 13,
    image: "/img/switzerland.jpg",
    title: "알프스 감성 가득한 스위스 여행",
    price: "₩ 2,299,000~",
    country: "Switzerland",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.8,
    reviewCount: 221,
    link: "/switzerland"
  },
  {
    id: 14,
    image: "/img/italy.jpg",
    title: "예술과 낭만의 이탈리아 여행",
    price: "₩ 2,099,000~",
    country: "Italy",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.7,
    reviewCount: 198,
    link: "/italy"
  },
  {
    id: 15,
    image: "/img/spain.jpg",
    title: "열정이 넘치는 스페인 여행",
    price: "₩ 1,989,000~",
    country: "Spain",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.6,
    reviewCount: 176,
    link: "/spain"
  },
  {
    id: 16,
    image: "/img/germany.jpg",
    title: "감성과 전통이 공존하는 독일 여행",
    price: "₩ 2,159,000~",
    country: "Germany",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.5,
    reviewCount: 164,
    link: "/germany"
  },
  {
    id: 17,
    image: "/img/austria.jpg",
    title: "음악과 풍경이 아름다운 오스트리아 여행",
    price: "₩ 2,189,000~",
    country: "Austria",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.7,
    reviewCount: 182,
    link: "/austria"
  },
  {
    id: 18,
    image: "/img/netherlands.jpg",
    title: "운하의 도시 네덜란드 여행",
    price: "₩ 2,049,000~",
    country: "Netherlands",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.4,
    reviewCount: 151,
    link: "/netherlands"
  },
  {
    id: 19,
    image: "/img/czech.jpg",
    title: "동화 같은 풍경의 체코 여행",
    price: "₩ 1,939,000~",
    country: "Czech Republic",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.6,
    reviewCount: 169,
    link: "/czech"
  },
  {
    id: 20,
    image: "/img/greece.jpg",
    title: "눈부신 지중해의 그리스 여행",
    price: "₩ 2,129,000~",
    country: "Greece",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.5,
    reviewCount: 158,
    link: "/greece"
  },
  {
    id: 21,
    image: "/img/newyork.jpg",
    title: "화려한 도시의 매력 뉴욕 여행",
    price: "₩ 2,399,000~",
    country: "USA",
    city: "New York",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.7,
    reviewCount: 245,
    link: "/newyork"
  },
  {
    id: 22,
    image: "/img/losangeles.jpg",
    title: "자유로운 감성의 로스앤젤레스 여행",
    price: "₩ 2,289,000~",
    country: "USA",
    city: "Los Angeles",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.6,
    reviewCount: 214,
    link: "/losangeles"
  },
  {
    id: 23,
    image: "/img/vancouver.jpg",
    title: "자연과 도시가 어우러진 밴쿠버 여행",
    price: "₩ 2,159,000~",
    country: "Canada",
    city: "Vancouver",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.5,
    reviewCount: 182,
    link: "/vancouver"
  },
  {
    id: 24,
    image: "/img/toronto.jpg",
    title: "세련된 도심 속 토론토 여행",
    price: "₩ 2,199,000~",
    country: "Canada",
    city: "Toronto",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.4,
    reviewCount: 169,
    link: "/toronto"
  },
  {
    id: 25,
    image: "/img/mexicocity.jpg",
    title: "전통과 열정이 살아있는 멕시코시티 여행",
    price: "₩ 1,989,000~",
    country: "Mexico",
    city: "Mexico City",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.3,
    reviewCount: 151,
    link: "/mexicocity"
  },
  {
    id: 26,
    image: "/img/rio.jpg",
    title: "열정의 해변 도시 리우 여행",
    price: "₩ 2,499,000~",
    country: "Brazil",
    city: "Rio de Janeiro",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.7,
    reviewCount: 203,
    link: "/rio"
  },
  {
    id: 27,
    image: "/img/saopaulo.jpg",
    title: "브라질의 활기를 느끼는 상파울루 여행",
    price: "₩ 2,359,000~",
    country: "Brazil",
    city: "Sao Paulo",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.2,
    reviewCount: 144,
    link: "/saopaulo"
  },
  {
    id: 28,
    image: "/img/lima.jpg",
    title: "역사와 미식이 공존하는 리마 여행",
    price: "₩ 2,189,000~",
    country: "Peru",
    city: "Lima",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.4,
    reviewCount: 137,
    link: "/lima"
  },
  {
    id: 29,
    image: "/img/santiago.jpg",
    title: "안데스의 풍경을 담은 산티아고 여행",
    price: "₩ 2,279,000~",
    country: "Chile",
    city: "Santiago",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.3,
    reviewCount: 129,
    link: "/santiago"
  },
  {
    id: 30,
    image: "/img/buenosaires.jpg",
    title: "낭만과 정열의 부에노스아이레스 여행",
    price: "₩ 2,469,000~",
    country: "Argentina",
    city: "Buenos Aires",
    type: "overseas",
    buttonText: "바로가기 〉",
    rating: 4.6,
    reviewCount: 158,
    link: "/buenosaires"

  }
] 